=== RohithEngu/VM27/clients/commands/src/main/resources/schemas/vmware-session.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.intalio.com/vmware/session" xmlns:session="http://www.intalio.com/vmware/session">
  <xs:element name="session">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="session:argument"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="session:activity"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="argument">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="activity">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="session:activity"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="session:argument"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RohithEngu/VM27/clients/commands/src/main/resources/schemas/vmware-session.xml
<?xml version="1.0"?>
<session xmlns="http://www.intalio.com/vmware/session" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.intalio.com/vmware/session file:///c:/Users/Administrator/Desktop/vmware-session.xsd">
   <argument name="name1">value1</argument>
   <activity name="activity1">
   <argument name="name1">value1</argument>
      <argument name="name2">value2</argument>
   </activity>
   <activity name="activity2">
	   <activity name="activity3">
		  <argument name="name3">value3</argument>
	   </activity>
	   <activity name="activity4">
		  <argument name="name4">value4</argument>
		  <argument name="name4">value4</argument>
	   </activity>
	   <activity name="activity5">
		  <argument name="name5">value5</argument>
	   </activity>
   </activity>
</session>
